package org.cis1200.monopoly;

public enum PropertyResponse {
    OK, INSUFFICIENT_FUNDS, NO_OWNER, NOT_OWNER, NO_HOUSES, MAX_HOUSES, ALREADY_OWNED, UNBALANCED_GROUP, NOT_GROUP_OWNER, ALREADY_MORTGAGED, NOT_MORTGAGED
}
